Sat 60 login api
Super-Amazing-Team/tower-defense pull request #13
Opened 2023-02-11 14:13 UTC by jodan13

### Какую задачу решаем
Подключить Регистрацию и Логин к API

![image](https://user-images.githubusercontent.com/17195611/218262623-1957e66f-f18e-462d-92c3-1f398e852428.png)

2023-02-11 14:42 UTC, Ax52 requested changes
Давай будем мерджить не в мейн, а, всё-таки, для начала, в рабочую ветку )

2023-02-11 15:32 UTC, Ax52 approved these changes
Как всегда - код на высоте! Для себя отметил нереактивный доступ к стору через `useStore.getState()`

2023-02-11 15:32 UTC, Ax52 commented on packages/client/src/store/userStore.ts
> +    { name: "userStore", version: 1.1 },
Круто, что ты не забыл обновить версию хранилища! Но пока мы еще ничего не влили в main ветку, то допустимо было бы и "позабыть" это сделать =-)

2023-02-11 15:50 UTC, itwassoclear approved these changes
Ура, можно залогиниться под старым аккаунтом от мессенджера :)
Спасибо, Евгений!

2023-02-12 09:32 UTC, glazkovpavel approved these changes

2023-02-12 10:28 UTC, merged