Sat 62 error boundary component
Super-Amazing-Team/tower-defense pull request #15
Opened 2023-02-12 09:48 UTC by itwassoclear

### Какую задачу решаем

Добавить перехват ошибок React компонентов

### Скриншоты/видяшка (если есть)

<img width="576" alt="Screenshot 2023-02-12 at 10 47 22" src="https://user-images.githubusercontent.com/27809896/218303951-756445b8-6bee-4e42-87e4-011a7ca241fe.png">

2023-02-12 14:35 UTC, glazkovpavel approved these changes

2023-02-13 08:30 UTC, jodan13 approved these changes

2023-02-13 11:01 UTC, Ax52 requested changes
Пожалуйста, перемести ErrorBoundary обертку из `main.tsx` файла в `app.tsx` файл.
Всё остальное классно!

2023-02-13 11:01 UTC, Ax52 commented on packages/client/src/utils/index.ts
> +export { ErrorBoundary } from "./ErrorBoundary";
Круто, что используешь реэкспорт компонентов для того чтобы их было проще импортировать и использовать!

2023-02-13 17:13 UTC, itwassoclear commented on packages/client/src/utils/index.ts
> +export { ErrorBoundary } from "./ErrorBoundary";
Жалко тебе лишнюю строчку кода...

2023-02-13 17:14 UTC, itwassoclear commented on packages/client/src/utils/ErrorBoundary.tsx
> +            color="primary"
Жалко тебе лишнюю строчку кода...

2023-02-13 17:43 UTC, jodan13 approved these changes

2023-02-13 18:12 UTC, Ax52 commented on packages/client/src/utils/ErrorBoundary.tsx
> +            color="primary"
Нет, не жалко ))
Скорее жалко твоё время )

2023-02-13 18:17 UTC, glazkovpavel approved these changes

2023-02-13 18:20 UTC, Ax52 approved these changes

2023-02-13 19:12 UTC, merged