Sat 76 hmr
Super-Amazing-Team/tower-defense pull request #29
Opened 2023-03-05 18:33 UTC by jodan13

### Какую задачу решаем
hmr

2023-03-05 20:35 UTC, arudenko-offcl commented on packages/server/src/index.tsx
> +declare const NO_SSR: boolean;
Глобальные переменные все же лучше объявлять в специально отведенном для этого месте, например в declaration files 🙂

2023-03-05 20:35 UTC, arudenko-offcl commented on packages/server/src/serverRenderer.tsx
> +      Object.values(ROUTE_CONSTANTS) as string[]
Здесь тайпкаст не нужен –тайпскрипт достаточно умен, чтобы взять тип из ROUTE_CONSTANTS

2023-03-05 20:35 UTC, arudenko-offcl commented on packages/server/src/serverRenderer.tsx
> +        <StaticRouter location={location}>
Нигде не используешь location больше, быть может обойтись без нее и передавать `req.url` ?

2023-03-05 20:35 UTC, arudenko-offcl commented on packages/server/src/serverRenderer.tsx
> +      req.url = ROUTE_CONSTANTS.notFound;
Все таки мутировать аргумент – не самая лучшая идея

2023-03-06 10:33 UTC, Ax52 commented on packages/server/.eslintrc.json
> +    "import/no-extraneous-dependencies": "off",
Не-не-не, давайте так не будем мьютить правила. Правила уже настроены в проекте и им стоит следовать, а не бороться с ними. я против таких изменений

2023-03-06 10:34 UTC, Ax52 commented on packages/server/src/index.tsx
> +declare const NO_SSR: boolean;
Конечно. это же глобал скоуп. значит и файл для таких деклараций должен быть один

2023-03-08 13:20 UTC, jodan13 commented on packages/server/.eslintrc.json
> +    "import/no-extraneous-dependencies": "off",
Правила созданы, что бы их нарушать!

2023-03-08 18:16 UTC, arudenko-offcl commented
Привет-привет! Все ли полнятно по моим комментам? Нужна помощь ?

2023-03-08 19:41 UTC, Ax52 commented
> Привет-привет! Все ли полнятно по моим комментам? Нужна помощь ?

@arudenko-offcl Привет! У нас сейчас 2/5 членов команды разъехались по командировкам, поэтому сейчас активность понизилась. Мы в команде обсудили этот пр: пока что остановились на том, что мы его пока (а может быть и вообще) не будем вливать в основную ветку.

2023-03-09 12:50 UTC, Ax52 requested changes

2023-03-09 12:50 UTC, Ax52 commented on packages/server/src/template.ts
> +            ${props.helmetData.meta.toString()}
Шаблонная строка и так конвертирует значения к строке )

2023-03-09 12:50 UTC, Ax52 commented on packages/server/tsconfig.json
> +    "experimentalDecorators": true,
где мы используем декораторы? Зачем включать эту опцию, если она фактически не используется?

2023-03-09 12:50 UTC, Ax52 commented on packages/server/webpack/client.config.ts
> +const withReport = Boolean(process.env.npm_config_withReport);
`process.env` значения это всегда - строки. Таким образом `!!"false"` || `!!"undefined"` будут давать ложноположительные значения

2023-03-09 12:50 UTC, Ax52 commented on packages/server/webpack/loaders/font.ts
> +const fontRegex = /\.(woff|woff2|ttf|otf|eot)$/;
У нас появились в проекте шрифты?)

2023-03-12 12:11 UTC, closed without merging