Sat 53 auth register pages
Super-Amazing-Team/tower-defense pull request #3
Opened 2023-02-04 15:49 UTC by jodan13

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-02-05 08:13 UTC, glazkovpavel submitted a review, later dismissed

2023-02-05 10:24 UTC, Ax52 requested changes
Ты проделал большую работу, ты молодец! Классный код!
Пожалуйста, зафиксируй версии новых зависимостей перед ПР.
Все остальные комментарии носят рекомендательный характер =-)

2023-02-05 10:24 UTC, Ax52 commented on packages/client/src/pages/Login/AuthLogin.tsx
> +import { MouseEvent, useState } from "react";
Если объект MouseEvent используется только как тип, то лучше его отдельно импортировать через
```suggestion
import type { MouseEvent } from "react";
import { useState } from "react";
```
потому что import type на этапе сборки выпиливается из проекта

2023-02-05 10:24 UTC, Ax52 commented on packages/client/src/pages/Login/AuthLogin.tsx
> +import * as z from "zod";
Круто, что ты используешь Zod в связке с react-hook-form!

2023-02-05 10:24 UTC, Ax52 commented on packages/client/src/utils/useLocalStorage.ts
> +export function useLocalStorage(key: string, defaultValue: string) {
Круто, что ты уже сделал кастомный хук для команды! 👍🏻

2023-02-05 15:30 UTC, jodan13 commented on packages/client/package.json
> +    "@hookform/resolvers": "^2.9.10",
+

2023-02-05 15:30 UTC, jodan13 commented on packages/client/src/App.test.tsx
> +// );
+

2023-02-05 15:30 UTC, jodan13 commented on packages/client/src/App.tsx
> +import Brightness7Icon from "@mui/icons-material/Brightness7";
+

2023-02-05 15:30 UTC, jodan13 commented on packages/client/src/App.tsx
> +  const theme = useMemo(
+

2023-02-05 15:30 UTC, jodan13 commented on packages/client/src/pages/Login/AuthLogin.tsx
> +import * as z from "zod";
+

2023-02-05 15:30 UTC, jodan13 commented on packages/client/src/utils/useLocalStorage.ts
> +export function useLocalStorage(key: string, defaultValue: string) {
+

2023-02-05 19:56 UTC, itwassoclear commented on packages/client/src/App.tsx
> +  const theme = useMemo(
Очень круто, что темизация заложена в самом начале!

2023-02-05 20:02 UTC, itwassoclear commented on packages/client/src/pages/Login/AuthLogin.tsx
> +              error={Boolean(errors.password)}
Было бы супер сделать так, чтобы появляющаяся ошибка под инпутом не влияла на положение инпута (сейчас он как бы отпрыгивает вверх если ошибка высвечивается)

2023-02-05 20:07 UTC, itwassoclear approved these changes

2023-02-06 06:39 UTC, kolosochek commented on packages/client/src/pages/Login/AuthLogin.tsx
> +import * as z from "zod";
А мне импорт по маске * не очень нравится, лучше импортировать те методы(классы, интерфейсы, etc) которые непосредственно используются, вместо импорта вообще всего

2023-02-06 06:42 UTC, kolosochek commented on packages/client/src/pages/Login/AuthLogin.tsx
> +              error={Boolean(errors.password)}
Удваиваю предыдущего оратора. 

Если мы инжектим в ДОМ какую-то ноду, она не должна рвать разметку, нужно либо классами задавать отступы и тогглить этот класс в зависимости от стейта, либо делать visibility: hidden на плейсхолдер с ошибкой, либо задавать min-height для контейнера.

2023-02-06 06:46 UTC, kolosochek commented on packages/client/src/pages/Login/AuthLogin.tsx
> +  const [showPassword, setShowPassword] = useState(false);
Я бы еще предложил переменные, которые явно булевого типа, называть с префикса is,
типа isShowPassword, setIsShowPassword и явно задавать типизацию для переменных стейта

типа вот так я предлагаю отрефакторить:
const [isShowPassword, setIsShowPassword] = useState<boolean>(false);

Зачем это нужно? По имени переменной понятно что это переключатель по сути, булевское значение, и в такую переменную состояния вообще не возникает желания ничего засунуть другого типа, отличного от булевого

2023-02-06 06:50 UTC, kolosochek submitted a review, later dismissed
Объем работы просто огромный. Спасибо за такой мощный вклад в общее дело.

2023-02-06 09:10 UTC, Ax52 approved these changes
Ты проделал большую работу! Быть первым - всегда тяжело (не у кого списать :D )

2023-02-06 10:06 UTC, itwassoclear approved these changes

2023-02-06 11:17 UTC, glazkovpavel approved these changes

2023-02-06 11:19 UTC, merged