Add home page layout
Super-Amazing-Team/tower-defense pull request #34
Opened 2023-03-22 11:32 UTC by itwassoclear

### Какую задачу решаем

Создание и вёрстка главной страницы

![Main (if user)](https://user-images.githubusercontent.com/27809896/226891644-7358dc5b-e2c3-4151-9197-6bd6619d65a0.png)

2023-03-22 11:50 UTC, glazkovpavel submitted a review, later dismissed

2023-03-23 08:57 UTC, arudenko-offcl submitted a review, later dismissed

2023-03-23 08:57 UTC, arudenko-offcl commented on packages/client/src/pages/Home/Home.tsx
> +            to={isAuth ? "/game" : "/login"}
Тут хорошо бы константу с роутами заюзать

2023-03-23 08:57 UTC, arudenko-offcl commented on packages/client/src/pages/Home/Home.tsx
> +            to="/leaderboard"
И тут тоже

2023-03-24 09:18 UTC, Ax52 requested changes
Привет! классная работа! Но парочка технических замечаний, которые впоследствие могут выступить в качестве чеховского ружья всё же нашлась. Пожалуйста, посмотри мои комменты и предложения по коду

2023-03-24 09:18 UTC, Ax52 commented on packages/client/src/pages/Home/Home.tsx
> +          backgroundImage: "url(../../../public/images/background.png)",
Не лучше ли было испортировать изображение и передать его в качестве шаблонной строки?) Так пути не потеряются в процессе бандлинга =-)
```suggestion
import backgroundImg from "../../../public/images/background.png";
// ...
          backgroundImage: `url(${backgroundImg})`,
```

2023-03-24 09:18 UTC, Ax52 commented on packages/client/src/pages/Home/Home.tsx
> +            backgroundImage: "url(../../../public/images/main-pic.png)",
Такое же предложение, что и выше

2023-03-24 09:18 UTC, Ax52 commented on packages/client/src/pages/Home/Home.tsx
> +            to={isAuth ? "/game" : "/login"}
Плюсую ) 
```suggestion
import { TRoutes as R } from "types";
// ...
            to={isAuth ? R.game : R.login}
```

2023-03-24 09:18 UTC, Ax52 commented on packages/client/src/pages/Home/Home.tsx
> +            to="/leaderboard"
```suggestion
import { TRoutes as R } from "types";
// ...
            to={R.leaderboard}
```

2023-03-24 09:18 UTC, Ax52 commented on packages/client/src/pages/Home/Home.tsx
> +              backgroundImage: "url(../../../public/images/water-tiles.gif)",
Тут также путь можно импортировать как ссылку (как и предложения выше)

2023-03-24 09:18 UTC, Ax52 commented on packages/client/src/pages/Home/Home.tsx
> +              key={Math.random()}
Какая гадость. Не надо так делать )

```suggestion
              key={crypto.randomUUID()}
```

2023-03-24 09:18 UTC, Ax52 commented on packages/client/src/pages/Home/Home.tsx
> +            <img src="../../../public/images/towerTwoBase-3.png" alt="Tower" />
Эти пути тоже лучше импортировать вначале файле

2023-03-24 09:18 UTC, Ax52 commented on packages/client/src/pages/Home/Home.tsx
> +              padding: "0 0 80px",
Вообще, такой подход имеетправо на жизнь, но mui во-первых имеет базовое значение пикселей, которым хорошо пользоваться чтобы верстка была пропорциональной, а во-вторых в mui есть сокращения =-)
```suggestion
              pr: 10,
```

2023-03-24 09:18 UTC, Ax52 commented on packages/client/src/pages/Home/Home.tsx
> +          >
Если шрифт много где используется, то в больших проектах было бы правильней создать отдельный вариант Typography при создании темы, который бы использовал нужный нам шрифт. В таком случае он бы автоматически использовался всякий раз, как мы бы указывали заранее определенный вариант

2023-03-24 09:18 UTC, Ax52 commented on packages/client/src/pages/Home/Home.tsx
> +            to={isAuth ? "/game" : "/login"}
Тут тоже лучше заюзать константы с роутами

2023-03-24 09:18 UTC, Ax52 commented on packages/client/src/pages/Home/ItemComponent.tsx
> +          backgroundImage: `url(../../../public/images/${image}.png)`,
лучше передавать не название, а сразу путь до файла, опять же, чтобы не потерялись пути при бандлинге

2023-03-24 09:18 UTC, Ax52 commented on packages/client/src/utils/ProtectedRoutes.tsx
> +    <Navigate to="/game" state={{ from: location }} replace />
```suggestion
import { TRoutes as R } from "types";
// ...
    <Navigate to={R.game} state={{ from: location }} replace />
```

2023-03-24 09:18 UTC, Ax52 commented on packages/client/src/utils/gameDetails.ts
> +      text: "д) обычный враг, скорпион. все параметры средние",
почему сразу добавляются элементы списка? может быть лучше ипользовать ненумерованный список уже при рендере?)

2023-03-24 09:40 UTC, Ax52 commented on packages/client/src/pages/Home/Home.tsx
> +              key={Math.random()}
А вообще во время рендера генерировать айдишник - это бесполезная срань. Он каждый раз всё равно будет новый. Тогда уж лучше использовать `tower.image` в качестве уникальный ключей

2023-03-24 10:52 UTC, kolosochek commented on packages/client/src/pages/Home/Home.tsx
> +  const { isAuth } = useUserStore((store) => store.user);
Я за первый вариант, за обычное присваивание без деструктуризации

2023-03-24 10:55 UTC, kolosochek commented on packages/client/src/utils/gameDetails.ts
> +      text: "д) обычный враг, скорпион. все параметры средние",
Наверно в какой-то итерации проекта разумно брать эти данные из движка, что бы при наведении на врага всплывал текст с описанием типа врага, его слабых\сильных сторон. Но как есть вполне. 

Другое дело что все изображения врагов у нас есть, и можно сделать их анимированными, типа не просто жук стоит, а idle-анимация(она есть в спрайтах). Но это может быть реализовано позднее

2023-03-24 10:57 UTC, kolosochek commented on packages/client/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">
Мы это, не можем использовать гуглошрифты, нужно их локально подключать, типа вот так:
<link
      href="./public/fonts/PressStart2P-Regular.ttf"
      rel="stylesheet"
    />

2023-03-24 10:59 UTC, kolosochek commented on packages/client/public/images/background.png
Можно не грузить дополнительную картинку, после инициализации движка можно получить изображение бекграунда как 
url("${engine.map?.grassBackrgroundCanvas?.toDataURL()}") repeat`;

2023-03-24 11:11 UTC, kolosochek commented on packages/client/src/pages/Home/ItemComponent.tsx
> +        sx={{
Можно еще снаружи компонента создать кастомную тему, типа вот так:

const theme = createTheme({
  components: {
    MuiTypography: {
      styleOverrides: {
        root: {
          color: "#ffae70",
          fontFamily: "'Press Start 2P', cursive",
        },
      },
    },
});

И потом завернуть весь рендер в провайдер темы, типа вот так:

return (
    <ThemeProvider theme={theme}>
    <Box />
    </ThemeProvider>

2023-03-24 11:12 UTC, kolosochek commented on packages/client/src/pages/Home/ItemComponent.tsx
> +        sx={{
Или повесить css селектор на содержимое родительского блока, типа как 
<Box sx={{
"& p": {
fontFamily: "'Press Start 2P', cursive",
}
}}
/>

2023-03-24 11:13 UTC, kolosochek approved these changes
Спасибо за большой объем проделанной работы, особенно когда знаешь сколько возни с нарезанием-сохранением-подгрузкой всех этих картиночек

2023-03-26 13:37 UTC, glazkovpavel approved these changes

2023-03-26 17:00 UTC, kolosochek commented on packages/client/index.html
> +    <link href="./public/fonts/PressStart2P-Regular.ttf" rel="stylesheet" />
можно подменить на /fonts/PressStart2P-Regular.ttf

2023-03-26 17:25 UTC, kolosochek commented on packages/client/src/pages/Home/Home.tsx
> +              padding: "152px 300px 100px",
Я бы вынес в селектор выше цвет шрифта типа, а то и тема есть и стили дублируются для каждого элемента
```
sx={{
"& p или & > *": {
color: "#104603",
}
}}
```

2023-03-26 17:39 UTC, kolosochek commented on packages/client/src/pages/Home/ItemComponent.tsx
> +          backgroundSize: "cover",
не знал шо такое бывает :0 Про contain и cover почитал. Познавательно.

2023-03-26 17:44 UTC, kolosochek approved these changes
You did a great job. Lijepo, hvala!

2023-03-26 18:05 UTC, arudenko-offcl reviewed
Хорошая работа.
Хорошей практикой будет заиспользовать fontFace и повторяющийся цвет

2023-03-26 18:05 UTC, arudenko-offcl commented on packages/client/index.html
> +    <link href="./public/fonts/PressStart2P-Regular.ttf" rel="stylesheet" />
Кастомные шрифты правильно подключать через директиву @fontFace
Подробнее тут: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face
Для materail-ui тут:https://mui.com/material-ui/customization/typography/#self-hosted-fonts

2023-03-26 18:05 UTC, arudenko-offcl commented on packages/client/src/pages/Home/Home.tsx
> +                color: "#104603",
Согласен, цвет шрифта необходимо унести в тему 
https://mui.com/material-ui/customization/color/

2023-03-26 18:57 UTC, jodan13 submitted a review, later dismissed

2023-03-26 19:09 UTC, jodan13 approved these changes

2023-03-26 19:10 UTC, glazkovpavel approved these changes

2023-03-27 10:24 UTC, Ax52 approved these changes
Еще одна таска закрыта!

2023-03-27 10:24 UTC, Ax52 commented on packages/client/src/pages/Home/Home.tsx
> +          }
То есть мы хардкодим этот шрифт во всём приложении, верно? и на кнопки и на менюхи, так?

2023-03-27 10:24 UTC, Ax52 commented on packages/client/src/pages/Home/Home.tsx
> +              onClick={() => scrollToElement("about")}
При использовании TS лучше максимально отказываться от использования строк напрямую. То есть здесь был смысл заюзать или readonly object (`const routes = {about: "about"} as const`) или enum. Это ни на что не повлияет, просто к сведению

2023-03-27 10:24 UTC, Ax52 commented on packages/client/src/pages/Home/Home.tsx
> +            </Typography>
Еще могу сказать что хорошая практика - выносить весь текст вовне(в отдельный JSON, js объект и тд), чтобы в будущем было проще подключать i18n. Но в нашем случае i18n не ожидается, так что ок

2023-03-27 10:24 UTC, Ax52 commented on packages/client/src/utils/ProtectedRoutes.tsx
> +    <Navigate to={R.game} state={{ from: location }} replace />
👍🏻

2023-03-27 10:24 UTC, Ax52 commented on packages/client/src/utils/gameDetails.ts
> +      image: "../../../public/images/towerTwoBase-1.png",
а вот тут импорты так и остались хардкоженными 🥸

2023-03-27 10:28 UTC, itwassoclear commented on packages/client/src/pages/Home/Home.tsx
> +          }
почему во всё приложении? это же тема только для главной страницы

2023-03-27 10:30 UTC, merged