Sprint 5
Super-Amazing-Team/tower-defense pull request #4
Opened 2023-02-05 10:29 UTC by Ax52

Ветка находится в процессе разработки, открыт draft pull request для того, чтобы ревьюеру из Яндекс было проще наблюдать промежуточный результат работы, чем ревьюить за раз весь спринт. Перед открытием основного ПР, в описание будет добавлено описание изменений

2023-02-07 20:40 UTC, arudenko-offcl commented
Друзья, привет!
Расскажите, как мы с вами работаем? Через куратора кажется получается немног осломанный телефон (

Вы будете держать ПР в статусе Draft пока не соберетесь вливать его, а я буду приходить и отсматривать с некоторой регулярностью ?

2023-02-08 08:59 UTC, Ax52 commented
> Друзья, привет! Расскажите, как мы с вами работаем? Через куратора кажется получается немног осломанный телефон (
> 
> Вы будете держать ПР в статусе Draft пока не соберетесь вливать его, а я буду приходить и отсматривать с некоторой регулярностью ?

Привет-привет!

Мы продолжительно и старательно приходили к консенсусу относительно порядка работы во 2ом модуле с командой Яндекса. В итоге, мы, совместно с куратором и "старшим экспертом по ревью" из Яндекс пришли к согласию о следующем порядке работ:

Мы с командой создаем в проекте _основную ветку_ `main`, мердж в которую будет производиться после твоего аппрува. В ветку `main` мы будем вливать __рабочую ветку текущего спринта__, в которой мы уже _работаем в своем режиме_, не дожидаясь тебя. В рабочую ветку мы с командой договорились вливать __фичеветки__, в которых каждый работает (как правило) индивидуально. Если тебе будет интересно, могу ассайнить тебе ревью __фичеветок__, но наше правило остаётся прежним: мы дожидаемся __3 аппрувов__ и вливаем фичеветку в рабочую (спринт). Я понимаю, что таким образом у тебя сложится отрывчатое впечатление о работе и не будет полного (надлежащего) контроля за разработкой. Однако подобное решение носит вынужденный характер; связанное в первую очередь с _сильной загруженностью_ каждого члена команды и _волнообразным характером командной разработки_ данного проекта. Все обсуждения процесса разработки, ПРов и коммитов ведутся в нашей команде __в командном мессенджере__, поэтому комментарии членов команды, аппрувы и код ревью здесь, на платформе GitHub _не могут отражать в полной мере вовлеченность членов команды в разработку_.

Чтобы тебе, как ревьюеру из Яндекс, __было удобнее__ наблюдать, комментировать и оставлять замечания относительно хода процесса разработки нашего приложения, не дожидаясь монструозного финального открытого ПРа из рабочей ветки в ветку `main`, я открыл черновик ПРа (этот) (который в конечном итоге и будет вливаться, __после твоего аппрува__), который будет своевременно обновляться при мердже фичеветок в рабочую. Конечно, и нам и тебе было бы проще, если бы ты ревьюил эту ветку _пропорционально поступающему в нее коду_, не дожидаясь окончания основных работ по спринту; Но, поскольку при существующем порядке работы, ожидание аппрува от ревьюера Яндекс (тебя) __не блокирует работу команды__, то можешь выбрать более подходящий и удобный для тебя порядок работы:
1) после обновления этой ветки я заново ассайню тебя на ревью и ты __постепенно ревьюишь__ поступающий код
2) в следующий раз я заасайню тебя на ревью этой ветки _только когда мы будем готовы_ вливать рабочую ветку в main и тебе __придется ревьюить весь код за раз__.

В надежде на скорейший ответ, 

С Уважением,
Лидер команды,
Александр Поляков.

2023-02-09 11:28 UTC, arudenko-offcl commented
@Ax52 
Кайф, мне все нравится. Меня немного сбивало с толку, что ПР все еще Draft, но я делаю вывод, что он превратится в рабочий, когда вы будете готовы вливать. 

Давайте работать по пункту 1! )

2023-02-09 11:31 UTC, arudenko-offcl commented
Так же хочу добавить, что SLA конечно будет повыше, чем 24 часа. 
Я тогда буду отмечаться, что я начал смотреть ПР и буду стараться укладываться в 48ч, но с конкретно здесь получится вероятно чуть больше. 
Александр, постарайся сделать итерации с призывом меня в ПР покороче, если получится )

И прошу отнестись с пониманием, наш с вами подход немного выбивается из обычного, принятого в Практикуме )

2023-02-09 12:24 UTC, Ax52 commented
@arudenko-offcl
Отдельно хотелось бы у тебя, как у ревьюера, уточнить __полный список обязательных требований для сдачи 5ого спринта__. Потому что единого мнения между ответственными лицами в Яндекс нет, а нашу работу принимать - тебе =-)
Было бы классно, если бы ты скинул буквально - _список_, а мы бы перед переводом этого ПР из черновика с ним бы сверились )

2023-02-14 17:13 UTC, arudenko-offcl requested changes
Друзья, простите за задержку! Старался вчитываться как следует) 

Справляетесь хорошо, даже круто! Очень нравится, что внимательно и даже придирчиво типизируете все.

Давайте обсудим и поправим все, о чем мне хочется поговорить )

- [ ] Я бы еще предложил положить yarn.lock в гитигнор и ad-hoc посмотреть в сторону [only-allow](https://www.npmjs.com/package/only-allow) подхода чтобы никто случайно не вернул yarn )
С гитигнроорм еще и дифф был бы не такой объемный)
Но это опционально, просто как идея вам. 


- [ ] Далее, вижу, что ответы апи никак не типизируются и результаты самонадеянно кладутся в стор. Надо подумать о валидации приходящих данных и типах. Иначе в стор можно полодить совершенно неожиданные вещи и даже не узнать об этом.

- [ ] Есть неплозой подход называть функции, реализующие обработчики событий через префикс `handle-`: handleClickItem, handleCloseDrawer . Это позволяет явно показать, что за функция перед нами и какой бизнес-смысл она несет
- [ ] Предлагаю начать использовать именованные импорты, например как в файле packages/client/src/pages/Login/AuthLogin.tsx .
- [ ] Нужно схемы данных вынести в отдельный раздел, где будет проще их переиспользовать и покрывать тестами.

2023-02-14 17:13 UTC, arudenko-offcl commented on packages/client/src/utils/dummySayHi.ts
> +// DELETE: this is an example file to represent exporting rules. It slould be removed before PR
**It slould be removed before PR** 🤔

2023-02-14 18:03 UTC, Ax51 commented on package.json
> +    "check": "pnpm dlx lefthook run pre-push",
Скрипт используется лично мной, чтобы проверять готовность кода перед отправкой (но не отправлять). Не вижу смысла дублировать команды из хука. В таком случае, если поменять команды в хуке - здесь команды не изменятся.  Считаю такой подход неправильным, потому что возникает несколько источников истины.

2023-02-14 18:04 UTC, Ax51 commented on packages/client/src/App.tsx
> +import { Layout } from "@/layout";
Согласен, поправим

2023-02-15 03:37 UTC, kolosochek commented on packages/client/src/App.tsx
> +import { Layout } from "@/layout";
Мне это не кажется хорошей идеей, сейчас структура проекта понятна, если делать реекспорт ухудшится читаемость как минимум

2023-02-15 03:38 UTC, kolosochek commented on packages/client/src/App.tsx
> +                    <Route path="/register" element={<Register />} />
Я предлагаю сделать интерфейс или тип для роутов, и явно типизировать пути

2023-02-15 03:39 UTC, kolosochek commented on packages/client/src/App.tsx
> +                      element={<Game engine={new TDEngine()} />}
Это и есть синглтон :)

2023-02-16 13:54 UTC, Ax52 commented on package.json
> +    "check": "pnpm dlx lefthook run pre-push",
Скрипт используется лично мной, чтобы проверять готовность кода перед отправкой (но не отправлять). Не вижу смысла дублировать команды из хука. В таком случае, если поменять команды в хуке - здесь команды не изменятся. Считаю такой подход неправильным, потому что возникает несколько источников истины.

2023-02-16 13:54 UTC, Ax52 commented on packages/client/src/App.tsx
> +import { Layout } from "@/layout";
Согласен, поправим

2023-02-16 13:54 UTC, Ax52 commented on packages/client/src/App.tsx
> +                    <Route path="/register" element={<Register />} />
Согласен, сделаем

2023-02-16 13:55 UTC, Ax52 commented on packages/client/src/utils/ProtectedRoutes.tsx
> +  const user = useUserStore((store) => store.user);
Можно и так, думаю что тут уже ты придираешься =-)

2023-02-16 13:56 UTC, Ax52 commented on packages/client/src/hooks/index.ts
> +// export { someFunction } from "./someFunction";
это шаблон, чтобы тиммейтам был пример для того, как использовать index.ts файл. Как только появится хук - поменяем )

2023-02-16 13:56 UTC, Ax52 commented on packages/client/src/layout/Header/Header.tsx
> +          }}
согласен, поправим

2023-02-16 13:59 UTC, Ax52 commented on packages/client/src/layout/Sidebar/Sidebar.tsx
> +        (event as KeyboardEvent).key === "Shift")
1) тут проверяется не сам эвент, а клавиша (`event.key`) =-)
2) операция создания массива, а также сам includes - это явно не перформас френдли решение =-) Особенно если эти две операции сравнивать с обычным побитовым равенством =-)

Поэтому здесь не согласен

2023-02-16 14:00 UTC, Ax52 commented on packages/client/src/layout/Sidebar/Sidebar.tsx
> +  const handlerLogout = () => {
Вероятно, но из одной строки не видно. Выделяй в следующий раз сразу весь обсуждаемый блок - так будет удобнее сразу смотреть на обсуждаемый код, не переключаясь в редактор )

2023-02-16 14:00 UTC, Ax52 commented on packages/client/src/layout/Sidebar/Sidebar.tsx
> +  const user = useUserStore((store) => store.user);
Это мы уже обсудили выше )

2023-02-16 14:01 UTC, Ax52 commented on packages/client/src/pages/Forum/Forum.tsx
> +        <Link to={"/forum/3"}>Topic 3</Link>
Вжух, и их уже нет в проекте! 🧙🏻‍♂️

2023-02-16 14:02 UTC, Ax52 commented on packages/client/src/pages/Game/enemies/Enemy.ts
> +      y: Math.floor(Math.random() * 15) + 1,
Не совсем ясно, что именно ты подразумеваешь под "дефолтным оффсетом". Это рандомный оффест спрайта врага относительно центра дороги. Так красивше (не все идут в ряд как по линейке)

2023-02-16 14:13 UTC, Ax52 commented on packages/client/src/pages/Login/AuthLogin.tsx
> +} from "@mui/material";
Думаем, что от стиля импортов работа приложения не меняется =-)

Но на эту тему есть одна статейка: https://mui.com/material-ui/guides/minimizing-bundle-size/

2023-02-16 14:15 UTC, Ax52 commented on packages/client/src/pages/Profile/Profile.tsx
> +  const logoutMe = () => {
вероятно. Но из выделенной части кода это не ясно. Пожалуйста, в следующий раз выделяй весь обсуждаемый блок кода )

2023-02-16 14:17 UTC, Ax52 commented on packages/client/src/pages/Register/AuthRegister.tsx
> +  const onSubmit = (data: TSchema) => {
и снова ничего не ясно из выделенного кода =-(

2023-02-16 14:19 UTC, Ax52 commented on packages/client/src/ui-component/index.ts
> +// export { someFunction } from "./someFunction";
Это шаблон. Для того, чтобы тиммейтам было проще понять как организовать реэкспорт

2023-02-16 14:19 UTC, Ax52 commented on packages/client/src/utils/Snackbar.tsx
> +      }, toast.duration || 6000);
ага, поправим )

2023-02-16 14:20 UTC, Ax52 commented on packages/client/src/utils/dummySayHi.ts
> +// DELETE: this is an example file to represent exporting rules. It slould be removed before PR
Да, спасибо что напомнил ) А то такие вещи часто забываются )

2023-02-16 14:34 UTC, Ax52 commented
@arudenko-offcl 
Привет! по замечаниям отписался. В основном вопросов нет, поправим. Я отписался инлайн к замечаниям. Также очень прошу тебя выделять ВЕСЬ обсуждаемый блок кода, а не первую его строку. Иначе без того чтобы залезть в редактор кода и искать ту самую обсуждаемую линию не обойтись. это очень неудобно.

По саммари (оно куда-то пропало, но интеренет помнит всё!):

=> _Давайте обсудим и поправим все, о чем мне хочется поговорить )_
Обсудим - да, а вот насчет поправить - сейчас обсудим =-)

=> _Я бы еще предложил положить yarn.lock в гитигнор и ad-hoc посмотреть в сторону [only-allow](https://www.npmjs.com/package/only-allow) подхода чтобы никто случайно не вернул yarn )
С гитигнроорм еще и дифф был бы не такой объемный)
Но это опционально, просто как идея вам._

Объясни пожалуйста, зачем добавлять безотносимые файлы в гитигнор? С таким же успехом в гитигнор можно добавить все .rs файлы и cargo (привет Rust). А также добавить в игнор bun-lock файл или package-lock файл или папку с мультиками для детей. Если этих файлов не предполагается в проекте, то зачем их добавлять в игнор? Неужели README недостаточно для того, чтобы понять, что в проекте используется pnpm? Считаю что это требование избыточно и не обосновано должным образом, поэтому на данный момент поправлять не будем.

=> _Далее, вижу, что ответы апи никак не типизируются и результаты самонадеянно кладутся в стор. Надо подумать о валидации приходящих данных и типах. Иначе в стор можно полодить совершенно неожиданные вещи и даже не узнать об этом._

Хорошо, поправим.

=> _Есть неплозой подход называть функции, реализующие обработчики событий через префикс handle-: handleClickItem, handleCloseDrawer . Это позволяет явно показать, что за функция перед нами и какой бизнес-смысл она несет_

Если вместо префикса handle используется on, то это уже плохой подход?)
Пожалуйста, уточни, про какие именно строки кода ты говоришь. Потому что инлайн замечаний на эту тему не было.

=> _Предлагаю начать использовать именованные импорты, например как в файле packages/client/src/pages/Login/AuthLogin.tsx ._

По именованным импортам отписался инлайн. Оба способа имеют право на жизнь, и никак не влияют на качество и работоспособность проекта.

=> _Нужно схемы данных вынести в отдельный раздел, где будет проще их переиспользовать и покрывать тестами._

Хорошо, сделаем =-)

2023-02-16 15:32 UTC, kolosochek commented on packages/client/src/pages/Game/enemies/Enemy.ts
> +    public enemyParams: IEnemy["enemyParams"] = {
Там и так сейчас отдельный интерфейс для каждого класса, который описывает переменные, которые я объявляю в конструкторе класса, и эти переменные типизированы интерфейсом.

Я предлагаю сменить тактику, я не вижу смысла комментировать ревью на код недельной(больше) давности, т.к. задача была проверить как оно ваще работает, это proof of concept. Я пушил из своего репозитория стабильный но старый код, пока мы его заапрувили в эту ветку, пока было сделано ревью, короче этого кода уже нет в проекте. 

Прямо сейчас я практически полностью переработал движок, для того что бы в него загрузить спрайты, процедурная генерация карты и пути врагов, поменялась физика движка, в корне изменился подход к отрисовке кадра, короче проще один раз увидеть чем про это подробно рассказывать.

Я создал драфт ПР https://github.com/Super-Amazing-Team/tower-defense/pull/19 и засуммонил @arudenko-offcl  туда, давайте попробуем так работу построить, буду раз в N дней делать драфт ПР и туда призывать ревьюера

2023-02-17 07:53 UTC, Ax52 commented
@arudenko-offcl 
Все (ну почти. Из тех, которые были оценены как допустимые.) твои хотелки, добавили, го аппрувить и двигаемся дальше. Чеклист по спринтам всё еще жду от тебя!

2023-02-17 17:02 UTC, arudenko-offcl commented on package.json
> +    "check": "pnpm dlx lefthook run pre-push",
РАзумно 👌

2023-02-17 17:03 UTC, arudenko-offcl commented on packages/client/src/utils/ProtectedRoutes.tsx
> +  const user = useUserStore((store) => store.user);
Я не придираюсь, а всего лишь  делюсь мыслями и открыт дискуссиям 🙂

2023-02-17 17:08 UTC, arudenko-offcl commented on packages/client/src/App.tsx
> +                      element={<Game engine={new TDEngine()} />}
Почему же, синглтон гарантирует доступ к единственному инстансу класса, а `new TDEngine()` всегда создает новый экземпляр 🙂

2023-02-17 17:14 UTC, arudenko-offcl commented on packages/client/src/layout/Sidebar/Sidebar.tsx
> +        (event as KeyboardEvent).key === "Shift")
> тут проверяется не сам эвент, а клавиша (event.key) =-)
Спасибо, что поправил! Рад, что несмотря на опечатку смысл остался понятен )

Второй пункт принимается 👌  
Но хочу, чтобы вы имели в виду, что стоит выдерживать баланс между перфомансом и читаемостью. Эту грань необходимо определить команде самостоятельно

2023-02-17 17:31 UTC, arudenko-offcl commented on packages/client/src/pages/Game/enemies/Enemy.ts
> +      y: Math.floor(Math.random() * 15) + 1,
Все так, **рандомный**, опечатка )

2023-02-17 18:29 UTC, arudenko-offcl approved these changes
Привет!

В ревью не только выдвигаются строгие требования или критические проблемы, но и темы к обсуждению, которые я нахожу важными. 

> - Если вместо префикса handle используется on, то это уже плохой подход?)

Нет, вроде я ничего об этом не писал 🙂

Замечание относится к подходу по именованию обработчиков событий. Я не стал их отмечать в ревью, тк встретил несколько вхождений и думаю, что директивно предложить ихз вам к обсуждению будет лучше:
https://jaketrent.com/post/naming-event-handlers-react/

Ну и на всякий случай пару мест отметил с ними.

> -Оба способа имеют право на жизнь, и никак не влияют на качество и работоспособность проекта.

Справедливо, и я не помечаю как must. Имеет смысл с целью добиться единообразия и читаемости внутри команды. Насколько это для вас важно – стоит решить команде.

> -очень прошу тебя выделять ВЕСЬ обсуждаемый блок кода

Понял, учту :ok_hand:

Отметил еще пару мест, вызвавших какие-либо вопросы у меня или просто оствленных без внимания и комментариев.

Коллеги, теперь – вижу, что некоторые вопросы относительно стиля написания кода вас тревожат несильно. Это вполне нормально, главное чтобы команда отдавала себе отчет в том, что ей необходимо,а что – нет. В таком случае, оставляю и буду их оставлять на ваше личное усмотрение. Тем не менее, не стесняйтесь вступать в дискуссию

Если будет что-то, что покажется мне критичным, то я поставлю реджект.

2023-02-17 18:29 UTC, arudenko-offcl commented on packages/client/src/layout/Sidebar/Sidebar.tsx
> +        onClick={closeDrawer}
Предложение по именованию обработчиков относится к этой строке например

2023-02-17 18:29 UTC, arudenko-offcl commented on packages/client/src/layout/Sidebar/Sidebar.tsx
> +        onKeyDown={closeDrawer}
Предложение по именованию обработчиков относится к этой строке например тоже

2023-02-17 18:29 UTC, arudenko-offcl commented on packages/client/src/App.tsx
> +import { TRoutes as R } from "./types";
НАзывать переменные одной буквой – плозая практика в js/ts 🙂

2023-02-17 18:29 UTC, arudenko-offcl commented on packages/client/src/types/routes.ts
> +} as const;
Для таких конструкций есть enum

2023-02-18 05:21 UTC, kolosochek commented on packages/client/src/pages/Game/enemies/Enemy.ts
> +         */
Старая версия кода

2023-02-18 05:23 UTC, kolosochek commented on packages/client/src/pages/Game/enemies/Enemy.ts
> +    }
Старая версия кода

2023-02-18 05:45 UTC, kolosochek commented on packages/client/src/pages/Game/enemies/Enemy.ts
> +  }
Старый код, вот как выглядит актуальная версия
https://github.com/Super-Amazing-Team/tower-defense/blob/sat-18_game-engine-mvp/packages/client/src/pages/Game/enemies/Enemy.ts

От early return я не отказываюсь, но использую там где считаю нужным

2023-02-18 05:46 UTC, kolosochek commented on packages/client/src/pages/Game/projectiles/Projectile.tsx
> +    }
Старый код

2023-02-18 05:49 UTC, kolosochek commented on packages/client/src/pages/Game/maps/Map.ts
> +}
Для явной типизации переменных класса. Теперь карта генерируется процедурно, например, и в этом же интерфейсе лежит типизация стейджей(этапов) по которым рисуется карта и идут враги. 

Кроме того, я придерживаюсь одного стиля декларативного(!) программирования. Одно явно проистекает из другого. Есть интерфейс, он явно описывает что и где должно лежать, затем в классе я это использую

2023-02-18 05:49 UTC, kolosochek commented on packages/client/src/pages/Game/towers/Tower.tsx
> +  };
Старый код

2023-02-18 05:50 UTC, kolosochek commented on packages/client/src/types/routes.ts
> +} as const;
Меня вполне устраивает тип(хотя я бы канеш сделал интерфейс, ну то такое), коллеги кто что думает?

2023-02-18 06:04 UTC, kolosochek commented on packages/client/src/App.tsx
> +                      element={<Game engine={new TDEngine()} />}
Если это не синглтон, то почему я при переходе на другой роут(с роута /game), возвращаюсь обратно на роут /game и в памяти вижу тот же самый инстанс TDEngine? С тем же количеством врагов, башен, пулек, денег и т.д.

Я даже видео записал
https://streamable.com/159x8r

Как на самом деле рендерятся роуты в react-router-dom v6? Рендерятся они каждый раз при переходе на роут? Или остаются в памяти что бы при каждом новом переходе на СТАТИЧЕСКИЙ роут, просто доставать его из памяти? 

Если последний вариант - то экземпляр класса TDEngine будет создан один раз, при первичном посещении роута, следовательно это первый и единственный инстанс на все приложение, == синглтон.

Я бы хотел подробнее узнать про то как на самом деле router-dom процессит маршруты, по идее если в пропсы передавать конструтор - он должен создавать новый экземпляр класса. По факту - нет.

2023-02-18 10:12 UTC, kolosochek commented on packages/client/src/App.tsx
> +                      element={<Game engine={new TDEngine()} />}
UPD: Я внимательно посмотрел код, подумал, твое предложение верное, так и было вначале, я создавал инстанс выше скоупом и передавал переменную со ссылкой на инстанс как значение пропса для компонента с игрой, и потом я решил что можно передавать конструктор, правильннее конечно первый вариант, я подпушил коммит в ветку с движком.

2023-02-18 11:27 UTC, Ax52 commented on packages/client/src/layout/Sidebar/Sidebar.tsx
> +        onClick={closeDrawer}
Думаю, это не влияет на работоспособность кода, а также не ухудшает его читаемость (что делает клик? закрывает Drawer. Прям очевидно ),поэтому тут оставим так )

2023-02-18 11:27 UTC, Ax52 commented on packages/client/src/layout/Sidebar/Sidebar.tsx
> +        onKeyDown={closeDrawer}
Думаю, это не влияет на работоспособность кода, а также не ухудшает его читаемость (что делает клик? закрывает Drawer. Прям очевидно ),поэтому тут оставим так )

2023-02-18 11:29 UTC, Ax52 commented on packages/client/src/App.tsx
> +import { TRoutes as R } from "./types";
Давай договоримся: если ты оспариваешь код, то ты будешь обосновывать свою позицию и подкреплять ее материалами =-)

Иначе, я абсолютно с такой же уверенностью могу сказать, что "называть переменные одной буквой - это ок", и в отсутствие обоснований каждой из позиций ни одна из них не будет иметь больший вес )

2023-02-18 12:00 UTC, Ax52 commented on packages/client/src/types/routes.ts
> +} as const;
> Для таких конструкций есть enum

Здесь также можно обратиться к комментарию выше.

Но в данном случае, свою позицию я подкреплю:
1) `ENUM` в TS это мёртворожденное дитя инцеста. Ты видел во что оно превращается на этапе компиляции, если `ENUM` использовать не только как тип, но и как значение? Если нет, посмотри.
2) Попробуй поспорить с [Matt Pocock](https://www.youtube.com/watch?v=jjMbPt_H3RQ) =-)

2023-02-18 12:08 UTC, Ax52 commented
@arudenko-offcl
Комментарии по движку сочтём неактуальными, потому что сам движок открыт в соседней ветке ПР, которую ты уже увидел. В остальном вижу, что критических замечаний нет, поэтому ПР отправляется в `main`

2023-02-18 12:14 UTC, jodan13 approved these changes

2023-02-18 12:57 UTC, itwassoclear approved these changes

2023-02-18 13:47 UTC, glazkovpavel approved these changes

2023-02-18 13:50 UTC, merged